str = "nandhini"
value = str.capitalize()
print(value)
value = str.casefold()
print(value)
value = str.isalpha()
print(value)
value = str.islower()
print(value)
value = str.isdigit()
print(value)
value = str.isprintable()
print(value)
value = str.isalnum()
print(value)
value = str.isdecimal()
print(value)
value = str.encode()
print(value)
value = str.endswith('.')
print(value)
value = str.expandtabs(20)
print(value)
value = str.index("and")
print(value)
value = str.find("hai")
print(value)
